name: Deploy

on:
  push:
    branches:
      - main
      - release/*
permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Set a Node.js version
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # pull code
      - name: Checkout code
        uses: actions/checkout@v3

      # using pnpm to install deps
      - run: npm i -g pnpm

      # build to static
      - name: Build Example
        run: pnpm install && pnpm build:app
        # working-directory: example

      # deploy to `docs` branch
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: dist
          silent: true
          clean: true
          branch: gh-pages
          single-commit: true